### ISSUE TITLE
可以考虑加一个隐藏开关吗

### ISSUE THREAD

**Issue by langkiss** [Xposed-Modules-Repo/com.lu.wxmask#1]
很好用，只是有时候我想看一下聊天记录需要进lsp里关闭再重启微信才能看，可以加一个隐藏式开关便捷显示/隐藏记录吗

**Comment by Mingyueyixi** [comment]
1. 重启lsp/微信    
可以不关 lsp 模块和微信。hook时设置了标记，从模块那移除掉配置，就生效了

2.临时隐藏开关or类似功能    
在后续版本添加，目前还没有。参考：https://github.com/Mingyueyixi/MaskWechat/issues/1
