### ISSUE TITLE
请问，那个临时解除到底怎么用啊？

### ISSUE THREAD

**Issue by sxakhyct** [Xposed-Modules-Repo/com.lu.wxmask#4]
我在配置中心里把临时解除的间隔调到1500毫秒，次数改为2次，但是我进一个人的聊天界面，快速双击和快速三击，再返回微信主界面，隐藏的聊天始终没有出现呀？

**Comment by mawkxcom** [comment]
需要在隐藏的聊天里点击，比如隐藏了和A的聊天记录，那么你需要在A的聊天框中点击

**Comment by sxakhyct** [comment]
> 需要在隐藏的聊天里点击，比如隐藏了和A的聊天记录，那么你需要在A的聊天框中点击

可是大哥，我都隐藏了和A的聊天，微信界面不显示A的聊天了，我怎么进入和A的聊天，再去双击取消隐藏呢？
目前的问题是隐藏了和A的聊天之后，不知道从哪儿打开和A的聊天界面，继续聊天了。请教一下

**Comment by Mingyueyixi** [comment]
从联糸人一个一个找，或朋友圈等入口进。并没有彻底隐藏
