### ISSUE TITLE
置顶聊天失效

### ISSUE THREAD

**Issue by mawkxcom** [Xposed-Modules-Repo/com.lu.wxmask#5]
微信版本：8.0.50
wxmask：2.3

刚注入之后是正常的，置顶聊天都会显示在最上方，使用了2、3天后，置顶聊天会被普通聊天顶下去，而且有时候会出现两个”订阅号“。忘修复

**Comment by Mingyueyixi** [comment]
当前版本不会修改置顶逻辑

**Comment by Mingyueyixi** [comment]
两订阅号是你使用了变脸模式。这功能会直接修改列表的id为指定id，默认id为订阅号id，你应该找个陌生人或未关注的朋友／公众号来填写，而不是用默认值

**Comment by mawkxcom** [comment]
> 两订阅号是你使用了变脸模式。这功能会直接修改列表的id为指定id，默认id为订阅号id，你应该找个陌生人或未关注的朋友／公众号来填写，而不是用默认值

嗯嗯 也是刚看完源项目地址的issue才知道 多谢

**Comment by mawkxcom** [comment]
> 当前版本不会修改置顶逻辑

好的 收到
